# Generated by Django 6.0.6 on 2026-06-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_required',
        ),
    ]
