# Generated by Django 6.0.6 on 2026-06-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_answer_text_answer_question_condition_option_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Один вариант'), ('multiple', 'Несколько вариантов'), ('scale', 'Шкала 1-10'), ('text', 'Текстовый ответ'), ('nps', 'NPS (0-10)')], default='single', max_length=10),
        ),
    ]
